sudo: false
language: python
cache: pip
python: 3.6
before_script:
- npm install -g html-minifier clean-css-cli
script:
- ./scripts/build
deploy:
- provider: script
  script: ./scripts/deploy
  on:
    branch: live
- provider: releases
  api_key:
    secure: KBrboqF3hVfcwxDmr/WdRyoD0Qqm3AwxvyUDX7CJuDecAVzZy0T+1pa84BZqIFSNhAS0Q/xVt9MeWziJJT1wc7Emj2991udfhFYR/5jmXvETNZwAnLmucY/xkCs31Xc35p8sI+PS2wb44yO8RMFdnac6WlEviLkaKlYx6u6jpnoIco+KW8yNusUiUcGJsA61NC7l1T0ALnK03eMIrIVCq5rWAk/ow0vJ7BOiGakGYBiO613RffFDO/1PPd1eGIF5aASniVuJKG8fRZ8rQZWYA8kQ16gHauZ/KarXpSTv67dVFTMflXZV2mWWP3+RQaFSRmPq0M/O6AYM+RpD6Ex5tOJxM4S1CoKsuxFYmtpDi58uudSAhAiAleO4mOh7m8RcR+XbJTKiUoBcC8NFvsj29bHklKNwdfwGq6JjiawN9mN0rCyV/2IjOk+0jbyaHAgf3A+9L/L7C10iz0jMeCs5BoflvOCn37udEvbB9BzySH2zMvCJff+lDvSf/pXsOS4KQn3NqbV3FNY++PFD4vp/KbKSsmrmE0Q8LcXA7/9IthOmaqzFw95NvHhcbEvOk5XFG+HLwXQ2vKcYMCUoc1ARom20VEllGV96WlX2Pje6dKsDO9SQSML0cuqVw2pQuxeWleWzjakd7Qx1uNdL63ua8Sapvt927eLcDFfyXepkCsQ=
  skip_cleanup: true
  file: /dev/shm/gebn.co.uk.tar.gz
  on:
    tags: true
