sudo: false
language: python
cache: pip
python: 3.6
before_script:
- npm install -g html-minifier clean-css-cli
script:
- ./scripts/build website /dev/shm/gebn.co.uk /dev/shm/gebn.co.uk.tar.gz
deploy:
- provider: script
  script: ./scripts/deploy gebn.co.uk /dev/shm/gebn.co.uk qa
  skip_cleanup: true
  on:
    repo: gebn/gebn.co.uk
    branch: qa
- provider: script
  script: ./scripts/deploy gebn.co.uk /dev/shm/gebn.co.uk prod
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key:
    secure: ume54lQRz/yeTYA23lSUsT0RCP6c/5jiLgfDDx6Nk7T2fo9I6ZJXkV22bm/FExl19PpL7JMJao0xsL4i1OUHWouJTJ7P56ybYH9F8wCQXzGcj+ChrT4wgqkfKidusDRD9OlFIi72oOBXNHbRcLOUYxnby8oPot/DbEAp9HdaqQYHqHCerc2bau5QyFz7F4gSWOWiVgFeAUZtmtPaFTLhY6yxSRKKdzmXESuAEylgdFAy/kCwHwVOrI5awzQ7COVPvuB6p8z8DVAh7ngLYLDL0JErJJR46+/zBA6zHrRCG+34/Prz4kkY2p9EY6uq8G/PStpNKj6Ps0M7usNVddM1MYu9OrbqA2liVE/3hmFwd4hSmAgF6AUBg9stjBUuqDVgFiPS0r5IbGU3RPIx9vMmdy2ovD5gGRgpt7NCxOY8ospzoSTIPuxT1VRha1qorB7eIyDB1SGudzJGOa0oOyuLSweAvhHd5IGZvPR3s73vImHjfd5aRtF1UWoFurcKvfdUYD/rhvLTm2dold4RiV8DFpGlX6WE1xXswFM7UimQBBFAZy6GKmwWSeAEL7dLPcMNmHAh+XpEzP9xZyGziqoFgVTfpummGmDyupu4JsH1KXN80ppFX+x3Cq7NX9+aWnz+w5DVwVmoCAG1nA1PqFx9Rvi/KPEYwvvUMHr80YXQRds=
  skip_cleanup: true
  file: /dev/shm/gebn.co.uk.tar.gz
  on:
    tags: true
