#!/bin/bash

trap 'exit' ERR

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/variables"

echo "Deploying ${DIST_NAME} to S3..."

if [[ ! -d $DIST_DIR ]]; then
    echo "Distribution directory does not exist" >&2
    exit 1
fi

cd "$DIST_DIR"  # to avoid "../../../../../dev/shm/..." in the log
# TODO do not depend on sizes being different - make timestamps work.
#      can you do a diff with the old live code and upload the changes?
aws s3 sync \
    --delete \
    --metadata git-commit="${TRAVIS_COMMIT:0:7}" \
    --no-follow-symlinks \
    --region "$S3_REGION" \
    --size-only \
    --storage-class "$S3_STORAGE_CLASS" \
    . "s3://$S3_BUCKET"
cd "$SCRIPT_DIR"

# TODO only invalidate changed files below (related to TODO above) (#3)

# flush CloudFront's cache
aws configure set preview.cloudfront true
aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_DISTRIBUTION" \
    --paths "/*"

# flush Cloudflare's cache
curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
     -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
     -H "X-Auth-Key: $CLOUDFLARE_KEY" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'
