#!/bin/bash
# Deploy this website to production

trap 'exit' ERR

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/variables"

if [[ -z $TRAVIS_TAG ]]; then
    echo "Only tags will be deployed to production" >&2
    exit 1
fi

if [[ ! -d $DIST_DIR ]]; then
    echo "Distribution directory does not exist" >&2
    exit 1
fi

echo "Deploying $DOMAIN:$TRAVIS_TAG to production..."

cd "$DIST_DIR"  # to avoid "../../../../../dev/shm/..." in the log
aws s3 sync \
    --delete \
    --no-follow-symlinks \
    --region "$S3_REGION" \
    --storage-class "$S3_STORAGE_CLASS" \
    . "s3://$S3_PROD_BUCKET"
cd "$SCRIPT_DIR"

# flush CloudFront's cache
aws configure set preview.cloudfront true
aws cloudfront create-invalidation \
    --distribution-id "$CLOUDFRONT_DISTRIBUTION" \
    --paths "/*"

# flush Cloudflare's cache
curl -X DELETE "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
     -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
     -H "X-Auth-Key: $CLOUDFLARE_KEY" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'

# Travis takes care of uploading the $DIST_ARCHIVE to the GitHub release
