#!/bin/bash
# Deploy the 'qa' branch to the QA bucket

trap 'exit' ERR

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/variables"

if [[ ! -d $DIST_DIR ]]; then
    echo "Distribution directory does not exist" >&2
    exit 1
fi

echo "Deploying $DOMAIN to qa..."

cd "$DIST_DIR"  # to avoid "../../../../../dev/shm/..." in the log
aws s3 sync \
    --delete \
    --no-follow-symlinks \
    --region "$S3_REGION" \
    --storage-class "$S3_STORAGE_CLASS" \
    . "s3://$S3_QA_BUCKET"
cd "$SCRIPT_DIR"

echo "Deployed to http://${S3_QA_BUCKET}.s3-website-${S3_REGION}.amazonaws.com"
